### ISSUE TITLE
startup delay

### ISSUE THREAD

**Issue by bluespider42** [TheDIYGuy999/MRSC_Adapter_WLtoys_5Pin_Servo#2]
I have followed the instructions given but I have been having a problem and wondered if you had any thoughts.
There seems to be a ~1.5 second delay between turning on the system and the output voltage from the arduino to the ESC stabilising. this means that the receiver tries to turn the servo too far before the feedback to the esc gets to the correct voltage.
When the arduino is not connected to the servo the output voltage settles within ~35ms of power on.
I have checked the values of both the resistor and capacitor (and experimented with different values).

**Comment by ustolt** [comment]
The start delay of about 1.46 seconds is caused by the Arduino Pro Mini  bootloader.

If you flash the optiboot / optiboot_atmega328.hex (https://github.com/Optiboot/optiboot/blob/master/optiboot/bootloaders/optiboot/optiboot_atmega328.hex), you get a boot time of about 68ms.

The blue line shows VCC, the yellow, the output of A10.

![bootloader_diff_original](https://user-images.githubusercontent.com/16761114/65332853-c2814900-dbbf-11e9-8a30-62ee9fbf75ab.png)

![bootloader_diff_optiboot](https://user-images.githubusercontent.com/16761114/65332871-c9a85700-dbbf-11e9-8625-1e79e8fa1aeb.png)

**Comment by owerlordalex** [comment]
![Аннотация 2020-04-07 135423](https://user-images.githubusercontent.com/63281949/78639112-974e1500-78d7-11ea-8ac2-e47abc84698a.png)

**Comment by owerlordalex** [comment]
when compiling, it displays an error

**Comment by owerlordalex** [comment]
please help

**Comment by owerlordalex** [comment]
![Аннотация 2020-04-07 140214](https://user-images.githubusercontent.com/63281949/78639604-776b2100-78d8-11ea-8f6e-b3e273665917.png)

**Comment by TheDIYGuy999** [comment]
Install PWMFrequency library

**Comment by owerlordalex** [comment]
can you please have a detailed video instruction on the firmware? I am from Russia and not strong in English

**Comment by owerlordalex** [comment]
sorry. really want to repeat your project

**Comment by TheDIYGuy999** [comment]
Sorry, I can't. Have a close look at the pictures for the wiring and use google translator for the comments in the sketch.

**Comment by owerlordalex** [comment]
I'll figure it out myself ...

**Comment by owerlordalex** [comment]
thanks
